### ISSUE TITLE
what does `mask` mean?

### ISSUE THREAD

**Issue by Halfish** [liu-nlper/SLTK#1]
https://github.com/liu-nlper/SLTK/blob/cc65f33ba0b5815fb874a8cf921b736b6b35bc4c/TorchNN/layers/crf.py#L224

**Comment by liu-nlper** [comment]
举个例子，当给定一个batch的gold_tags要求算该tags的得分的时候，由于batch中每个实例的实际长度都不相等，那些用`0`补全的地方是不需要计算得分的，所以需要用到mask

**Comment by Halfish** [comment]
Got it, thanks.

______
Sorry about my broken Sogou in Ubuntu.
