### ISSUE TITLE
 invalid argument 0: Tensors must have same number of dimensions: got 3 and 2 

### ISSUE THREAD

**Issue by blackbbc** [liu-nlper/SLTK#12]
如果一个batch里数据恰好为1，则 `torch.cat`操作会将第1维裁剪掉，导致`word_feature`与`char_feature`维度不一致报错

https://github.com/liu-nlper/SLTK/blob/b3edc58ef1d317eefc21e65d306932dedc6a8525/sltk/nn/modules/sequence_labeling_model.py#L130

**Comment by dalinvip** [comment]
前段时间也发现了這个问题，改一下這个应该就ok啦
`pool_output = torch.squeeze(torch.max(conv_output, -2)[0], -1)`
[ SLTK/sltk/nn/modules/feature.py](https://github.com/liu-nlper/SLTK/blob/b3edc58ef1d317eefc21e65d306932dedc6a8525/sltk/nn/modules/sequence_labeling_model.py#L130)
