### ISSUE TITLE
RuntimeError: dimension specified as 0 but tensor has no dimensions

### ISSUE THREAD

**Issue by cyzhangAThit** [liu-nlper/SLTK#3]
Hi, I run your code on pytorch 0.3. I found in your data set , I can run the code successfully.  But in my own dataset or the data created by the head 200 lines in your dataset,  the code run failed with the Error:
"RuntimeError: dimension specified as 0 but tensor has no dimensions"

**Comment by liu-nlper** [comment]
Hi,

Thanks for pointing out the preblem, if you use pytorch 0.3, try to change
the code in `TorchNN/layers/crf.py` at line 87-90:

*    masked_cur_partition = cur_partition.masked_select(mask_idx)*
*    mask_idx = mask_idx.contiguous().view(batch_size, tag_size, 1)*
*    partition.masked_scatter_(mask_idx, masked_cur_partition)*

*to*


*     masked_cur_partition = cur_partition.masked_select(mask_idx)    if
masked_cur_partition.dim() != 0:        mask_idx =
mask_idx.contiguous().view(batch_size, tag_size, 1)
partition.masked_scatter_(mask_idx, masked_cur_partition) *
I will fix this bug in next version.

best regards

**Comment by cyzhangAThit** [comment]
thanks for your suggestion. But can you help me to indent your code correctly, please?

**Comment by liu-nlper** [comment]
@cyzhangAThit sorry...
masked_cur_partition = cur_partition.masked_select(mask_idx)
if masked_cur_partition.dim() != 0:
    mask_idx = mask_idx.contiguous().view(batch_size, tag_size, 1)
    partition.masked_scatter_(mask_idx, masked_cur_partition)

**Comment by liu-nlper** [comment]
@cyzhangAThit 
    masked_cur_partition = cur_partition.masked_select(mask_idx)
    if masked_cur_partition.dim() != 0:
        mask_idx = mask_idx.contiguous().view(batch_size, tag_size, 1)
        partition.masked_scatter_(mask_idx, masked_cur_partition)

**Comment by liu-nlper** [comment]
@cyzhangAThit 
```
masked_cur_partition = cur_partition.masked_select(mask_idx)
if masked_cur_partition.dim() != 0:
    mask_idx = mask_idx.contiguous().view(batch_size, tag_size, 1)
    partition.masked_scatter_(mask_idx, masked_cur_partition)
```

**Comment by cyzhangAThit** [comment]
I'm sorry again now.
After training the model as your suggestion, I try to test the model.
But I get the error like this:

TorchNN/layers/crf.py", line 130, in _viterbi_decode
    mask = 1 + (-1) * mask
RuntimeError: value cannot be converted to type uint8_t without overflow: -1

It seems the data type is wrong.
