### ISSUE TITLE
请教po主：能否增加对valid集和test集的测试结果统计啊?

### ISSUE THREAD

**Issue by muzier** [liu-nlper/SLTK#7]
如题：目前的test下的infer方法是直接写成了文件，能否有对test结果的统计report啊？包括验证集也是。刚接触pytorch，还不太了解，请po主多指教~

**Comment by liu-nlper** [comment]
你好，在SLTK/tools下有个conlleval
<https://github.com/liu-nlper/SLTK/blob/master/tools/conlleval>
脚本可以完成评测，你可以看下

**Comment by muzier** [comment]
好的，没想到这么快就回复啦，非常感谢！

**Comment by Biaocsu** [comment]
@muzier 您好，请问conlleval脚本该怎样运行使用啊，小白弄了半天也没弄明白
