### ISSUE TITLE
再次请教：在中文标注任务中，使用预训练词向量的OOV数量很大，是否正常？

### ISSUE THREAD

**Issue by muzier** [liu-nlper/SLTK#8]
再次请教po主：我在做中文标注的任务训练，发现使用预训练词向量的匹配结果中，OOV的占比很大，是不是因为中文的词向量很多是分词之后的两字词、三字词四字词，而训练语料train.txt中的标记都是单字，所以导致OOV比较多啊？下面这种情况是否正常？是否可以继续训练呢？
抽取预训练词向量...
特征`word`使用预训练词向量`./data/word2vec.txt`:
        精确匹配: 3365 / 7099
        模糊匹配: 4 / 7099
        OOV: 3730 / 7099
先谢过啦~~~

**Comment by liu-nlper** [comment]
这个比例的OOV是有点大了，你是做中文的什么任务？如果是中文NER，一般从字符层面做，不用先分词，即使分词，分词也是作为一个特征

**Comment by muzier** [comment]
是中文的NER任务，如果直接从字符层面做，那是不是就不需要embedding的词向量了？直接 pretrain--train--test就可以吗？

**Comment by liu-nlper** [comment]
可以使用预训练的字向量

**Comment by muzier** [comment]
是呀，晕死。。。谢谢啦！

**Comment by Daniel19960601** [comment]
> 是呀，晕死。。。谢谢啦！

请问您在中文数据集上跑到了结果吗？
我是用msra数据集，loss不降反升，不知道什么原因。然后到patience值就停了。
![image](https://user-images.githubusercontent.com/20382469/109587120-7cb10a00-7b41-11eb-99e3-36a71a8cb244.png)
